### ISSUE TITLE
repeated compilation fails due to pipe errors

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#397]
When compiling the same project several times in a row, subsequent compilations usually fail with error logs containing messages like "Pipe closed" or "Pipe broken". This is apparently a side effect of pull request #375.

**Comment by odisseus** [comment]
It turns out that the `compile` command may create a BSP connection more than once. Sometimes only one of these connections throws an exception.

**Comment by propensive** [comment]
I merged what should be a fix for this. It's difficult to test, as the broken-pipe errors weren't happening consistently, but let's reopen this if it turns out not to work.

**Comment by odisseus** [comment]
The pipe errors still happen sometimes, especially during the cloud build:
```
----------------------------------------------------------------------------------------------------
 build-zio: Build ZIO from source
----------------------------------------------------------------------------------------------------
Cloning repository at https://github.com/propensive/.scala.git
Checking out * from repository scala
Resolving org.openjdk.jcstress:jcstress-core:0.4
Resolving org.specs2:specs2-core_2.12:4.7.1
Resolving org.specs2:specs2-matcher-extra_2.12:4.7.1
Resolving org.specs2:specs2-scalacheck_2.12:4.7.1
Resolving com.github.ghik:silencer-lib_2.12:1.4.2
Cloning repository at https://github.com/zio/zio.git
Checking out {core/jvm/src/main/java, core/jvm/src/main/scala, core/jvm/src/main/scala-2.12, core/shared/src/main/scala, core/shared/src/main/scala-2.12+} from repository zio
Checking out core/jvm/src/main/java from repository zio
Checking out {stacktracer/jvm/src/main/scala, stacktracer/shared/src/main/scala} from repository zio
Checking out {streams/jvm/src/main/scala, streams/shared/src/main/scala} from repository zio
Cloning repository at https://github.com/portable-scala/portable-scala-reflect.git
Checking out jvm/src/main/java from repository portable-scala-reflect
Checking out {test/jvm/src/main/scala, test/jvm/src/test/scala, test/shared/src/main/scala, test/shared/src/test/scala} from repository zio
Checking out jvm/src/main/scala from repository portable-scala-reflect
Problem with the build server: 'org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Pipe closed'.
  at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
  at java.io.PipedInputStream.receive(PipedInputStream.java:226)
  at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
  at java.io.OutputStream.write(OutputStream.java:75)
  at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
  at org.eclipse.lsp4j.jsonrpc.Launcher$Builder.lambda$wrapMessageConsumer$0(Launcher.java:312)
  at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.request(RemoteEndpoint.java:161)
  at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:91)
  at com.sun.proxy.$Proxy4.buildTargetCompile(Unknown Source)
  at fury.core.Compilation.$anonfun$compileModule$4(data.scala:705)
  at fury.core.Compilation.$anonfun$wrapServerErrors$2(data.scala:717)
  at fury.strings.Outcome$Rescue.apply(outcome.scala:29)
  at fury.core.Compilation.wrapServerErrors(data.scala:717)
  at fury.core.Compilation.$anonfun$compileModule$3(data.scala:705)
  at fury.core.BspConnection.provision(data.scala:183)
  at fury.core.Compilation.$anonfun$compileModule$2(data.scala:704)
  at fury.utils.Pool.$anonfun$borrow$3(pool.scala:63)
  at scala.util.Success.$anonfun$map$1(Try.scala:255)
  at scala.util.Success.map(Try.scala:213)
  at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
  at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
  at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
1
An unexpected error occurred which has been logged to /home/bash_user/test/tmp/build-zio/.fury/logs/2019-10-16-11:53:07.669-4ec6a166-8a29-49c9-9b2a-c6eebed04c7e.log
1

```

**Comment by propensive** [comment]
I haven't seen these errors for a very long time.
